const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Touch,
		C3.Plugins.Sprite,
		C3.Plugins.Browser,
		C3.Behaviors.Tween,
		C3.Behaviors.Pin,
		C3.Behaviors.DragnDrop,
		C3.Plugins.Mouse,
		C3.Plugins.AJAX,
		C3.Plugins.Audio,
		C3.Plugins.Arr,
		C3.Plugins.Json,
		C3.Plugins.Text,
		C3.Behaviors.Flash,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Browser.Acts.RequestFullScreen,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Browser.Acts.CancelFullScreen,
		C3.Plugins.Browser.Acts.GoToURL,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.Arr.Acts.SetSize,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.AJAX.Acts.RequestFile,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.Json.Acts.Parse,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Plugins.Sprite.Cnds.CompareOpacity,
		C3.Plugins.Sprite.Acts.SetEffectEnabled,
		C3.Plugins.Touch.Cnds.IsInTouch,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Exps.ImagePointX,
		C3.Plugins.Sprite.Exps.ImagePointY,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.System.Acts.SetVar,
		C3.Behaviors.Pin.Acts.Unpin,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.Sprite.Exps.BBoxLeft,
		C3.Plugins.Sprite.Exps.BBoxRight,
		C3.Plugins.Sprite.Exps.BBoxTop,
		C3.Plugins.Sprite.Exps.BBoxBottom,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Behaviors.DragnDrop.Cnds.IsDragging,
		C3.Behaviors.DragnDrop.Cnds.OnDrop,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Cnds.PickDistance,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Behaviors.DragnDrop.Cnds.OnDragStart,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Sprite.Cnds.IsOutsideLayout,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.Arr.Acts.Push,
		C3.Plugins.Json.Exps.Get,
		C3.Plugins.Arr.Exps.At,
		C3.Behaviors.DragnDrop.Acts.SetEnabled,
		C3.Plugins.Arr.Exps.Width,
		C3.Plugins.Arr.Acts.Delete,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Arr.Cnds.CompareSize,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.System.Exps.loadingprogress,
		C3.Plugins.System.Acts.GoToLayout
	];
};
self.C3_JsPropNameTable = [
	{Touch: 0},
	{refreshBtn: 0},
	{audioBtn: 0},
	{shareBtn: 0},
	{fullScreenBtn: 0},
	{Browser: 0},
	{loaderEmpty: 0},
	{Tween: 0},
	{loaderFill: 0},
	{loaderLogo: 0},
	{arkaplan: 0},
	{kordinatBg: 0},
	{kordinatGrid: 0},
	{kordinat: 0},
	{isActive: 0},
	{ucUcaBtn: 0},
	{paralelBtn: 0},
	{gridBtn: 0},
	{silBtn: 0},
	{okBtn: 0},
	{isResizeable: 0},
	{arrowUID: 0},
	{isCounted: 0},
	{okLine: 0},
	{okUID: 0},
	{Pin: 0},
	{DragDrop: 0},
	{okArrow: 0},
	{Mouse: 0},
	{vektorLine1: 0},
	{vektorArrow1: 0},
	{vektorLine2: 0},
	{vektorArrow2: 0},
	{indexX: 0},
	{indexY: 0},
	{point: 0},
	{dash: 0},
	{nextBtn: 0},
	{prevBtn: 0},
	{vektorLine3: 0},
	{vektorArrow3: 0},
	{AJAX: 0},
	{Audio: 0},
	{randomArray: 0},
	{polarJSON: 0},
	{Flash: 0},
	{Text: 0},
	{gameButtons: 0},
	{vektors: 0},
	{vektorArrows: 0},
	{isDragging: 0},
	{snapControl: 0},
	{paralelMode: 0},
	{unHoldUcucaMode: 0},
	{vektorOffsetY: 0},
	{vektorOffsetX: 0},
	{ucUcaCount: 0},
	{firstUcUcaVektorUID: 0},
	{secondUcUcaVektorUID: 0},
	{thirdUcUcaVektorUID: 0},
	{firstUcucaX: 0},
	{firstUcucaY: 0},
	{secondUcucaX: 0},
	{secondUcucaY: 0},
	{sizeX: 0},
	{sizeY: 0},
	{posX: 0},
	{posY: 0},
	{dashLength: 0},
	{dashAngle: 0},
	{layer: 0},
	{crossCheckSondan: 0},
	{crossCheckBastan: 0},
	{newFirstVektorUID: 0},
	{a: 0},
	{b: 0},
	{c: 0},
	{d: 0},
	{firstX: 0},
	{firstY: 0},
	{secondX: 0},
	{secondY: 0},
	{isLoader: 0}
];

self.InstanceType = {
	Touch: class extends self.IInstance {},
	refreshBtn: class extends self.ISpriteInstance {},
	audioBtn: class extends self.ISpriteInstance {},
	shareBtn: class extends self.ISpriteInstance {},
	fullScreenBtn: class extends self.ISpriteInstance {},
	Browser: class extends self.IInstance {},
	loaderEmpty: class extends self.ISpriteInstance {},
	loaderFill: class extends self.ISpriteInstance {},
	loaderLogo: class extends self.ISpriteInstance {},
	arkaplan: class extends self.ISpriteInstance {},
	kordinatBg: class extends self.ISpriteInstance {},
	kordinatGrid: class extends self.ISpriteInstance {},
	kordinat: class extends self.ISpriteInstance {},
	ucUcaBtn: class extends self.ISpriteInstance {},
	paralelBtn: class extends self.ISpriteInstance {},
	gridBtn: class extends self.ISpriteInstance {},
	silBtn: class extends self.ISpriteInstance {},
	okBtn: class extends self.ISpriteInstance {},
	okLine: class extends self.ISpriteInstance {},
	okArrow: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	vektorLine1: class extends self.ISpriteInstance {},
	vektorArrow1: class extends self.ISpriteInstance {},
	vektorLine2: class extends self.ISpriteInstance {},
	vektorArrow2: class extends self.ISpriteInstance {},
	point: class extends self.ISpriteInstance {},
	dash: class extends self.ISpriteInstance {},
	nextBtn: class extends self.ISpriteInstance {},
	prevBtn: class extends self.ISpriteInstance {},
	vektorLine3: class extends self.ISpriteInstance {},
	vektorArrow3: class extends self.ISpriteInstance {},
	AJAX: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	randomArray: class extends self.IArrayInstance {},
	polarJSON: class extends self.IJSONInstance {},
	Text: class extends self.ITextInstance {},
	gameButtons: class extends self.ISpriteInstance {},
	vektors: class extends self.ISpriteInstance {},
	vektorArrows: class extends self.ISpriteInstance {}
}